# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

sphinx:
    configuration: docs/conf.py

# xcffib must be installed first
python:
    version: 3.8
    install:
        - requirements: .xcffib
        - requirements: requirements.txt
        - requirements: docs/requirements.txt
    system_packages: true
